# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        def test_valid_username():
          assert is_valid_username("john_doe")
          assert not is_valid_username("john doe")
          assert not is_valid_username("")
        def test_valid_password():
          assert is_valid_password("P@ssw0rd")
          assert not is_valid_password("password")
          assert not is_valid_password("12345678")
          assert not is_valid_password("P@ssw0r")
          assert is_valid_password("P@ssword123")
          
        def test_valid_email():
          assert is_valid_email("john@example.com")
          assert not is_valid_email("john@com")
          assert not is_valid_email("john@example")
          assert not is_valid_email("john@examplecom")
        
        pytest
